c_compiler_version:      # [osx]
  - 14                   # [osx]
MACOSX_SDK_VERSION:      # [osx]
  - 11.1                 # [osx]
CONDA_BUILD_SYSROOT:     # [osx]
  - /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk  # [osx]