{% set name = "maturin" %}
{% set version = "0.13.3" %}

package:
  name: {{ name }}-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: edeb8ecaa5cc6e6d2f50a32289798d7ca046c33481ac24f74805ff289af6afe4

build:
  number: 0
  # ring (dependency loaded via cargo) is not supported on s390x yet
  # https://github.com/briansmith/ring/issues/1511
  skip: True  # [py<37 or s390x]


outputs:
  - name: {{ name }}
    script: bld-win.bat                  # [win]
    script: build-unix.sh                # [not win]
    missing_dso_whitelist:   # [osx]
      - /usr/lib/libresolv.9.dylib  # [osx]
    requirements:
      host:
        - pip
        - python
        - setuptools
        - setuptools-rust >=1.4.0
        - wheel >=0.36.2
        - tomli >=1.1.0
      run:
        - python
        - tomli >=1.1.0
      build:
        - {{ compiler('c') }}
        - {{ compiler('rust') }}     # [not win]
        - rust_win-64                # [win]
    test:
      commands:
        - maturin --help
  - name: {{ name }}-gnu               # [win]
    script: bld-win.bat                # [win]
    requirements:                      # [win]
      host:                            # [win]
        - pip                          # [win]
        - python                       # [win]
        - setuptools                   # [win]
        - setuptools-rust >=1.4.0      # [win]
        - wheel >=0.36.2               # [win]
        - tomli >=1.1.0                # [win]
      run:                             # [win]
        - python                       # [win]
        - tomli >=1.1.0                # [win]
      build:                           # [win]
        - {{ compiler('m2w64_c') }}    # [win]
        - rust-gnu_win-64              # [win]
    test:                              # [win]
      requires:                        # [win]
        - posix                        # [win]
      commands:                        # [win]
        - maturin --help               # [win]

about:
  home: https://maturin.rs/
  license: MIT and Apache-2.0
  license_family: MIT
  license_file: license-mit
  summary: >-
    Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages
  dev_url: https://github.com/PyO3/maturin
  doc_url: https://maturin.rs/

extra:
  recipe-maintainers:
    - apcamargo
